import os
from docx import Document
import requests
from dotenv import load_dotenv
from IPython.display import Markdown, display
from typing_extensions import TypedDict
from agents import Agent, Runner, function_tool, SQLiteSession
from openai import OpenAI
from pydantic import BaseModel

load_dotenv()

api_key = os.getenv("OPENAI_API_KEY")
tavily_api_key = os.getenv("TAVILY_API_KEY")
model = os.getenv("MODEL")

# print(f"Using model: {model}")
# print(f"Tavily API Key: {tavily_api_key if tavily_api_key else 'Not Set'}")
# print(f"OpenAI API Key: {api_key if api_key else 'Not Set'}")

# print markdown
def print_markdown(text):
    """Utility function to print text in markdown format."""
    display(Markdown(text))


class TavilySearchParams(TypedDict):
    """Parameters for the Tavily search function."""
    query: str
    max_results: int = 3


@function_tool
def tavily_search(params: TavilySearchParams) -> str:
    """Searches for information using the Tavily API."""

    url = "https://api.tavily.ai/search"

    headers = { 
        "Content-Type": "application/json",
    }
    
    payload = {
        "q": params.query, 
        "key": tavily_api_key
    }
    
    resp = requests.post(url, json=payload, headers=headers)

    if resp.status_code != 200:
        return f"Tavily API Error: {resp.json().get('error', 'Unknown error occurred.')}"

    data = resp.json()
    if "results" not in data:
        return "No results found."

    lines = []
    for i, r in enumerate(data["results"][:params.max_results], start=1):
        lines.append(f"{i}. **{r['title']}**: {r['snippet']}")
    return "\n".join(lines)

# print("Tavily search tool ready!\n")


# Lets define researcher agent 
# define pydantic model for researcher agent input
class AnalysisSummary(BaseModel):
    summary: str

researcher_agent = Agent(
    name="Researcher AI",
    instructions="""
        Context: 
        You are a research agent with access to the tavily search tool.
        
        Instruction: Collect detailed and accurate information about the given topic.
        
        Input: a user query on a specific topic.
        
    """,
    tools=[tavily_search],
    model=model,
    output_type=AnalysisSummary
)
# print(f"{researcher_agent.name} Agent created successfully!\n")

# async def runTask():
#     researcher_result = await Runner.run(
#         starting_agent=researcher_agent,
#         input="What are the health benefits of turmeric?"
#     )
#     if researcher_result.final_output:
#         return researcher_result

# result = runTask()


input_text = input("Enter your query please!")

print(f"### Running Researcher Agent to gather information on '{input_text}' ### \n")

result = Runner.run_sync(
    starting_agent=researcher_agent,
    input=input_text
)

# print("### Researcher Agent Output ### \n")
# print(result.final_output.summary)

# Analyst Agent
analyst_agent = Agent(
    name="Analyst AI",
    instructions="""
        Context: 
        You are a analyst who recieves research notes from the researcher agent.
        
        Instruction:
        Given the research notes from the researcher agent, your task is to analyze the 
        information and provide a concise summary that captures the key insights and findings. 
        
        Input:
        Research notes provided by the researcher agent on a specific topic.

        Output:
        A concise summary no more than 2 paragraphs that captures the key insights, risks and findings from the research notes.
        
    """,
    tools=[tavily_search],
    model=model,
    output_type=AnalysisSummary
)
# print(f"{analyst_agent.name} Agent created successfully!\n")

print(f"### Running Analyst Agent to analyze research notes provied by Researcher Agent on '{input_text}'? ### \n")
analysis_result = Runner.run_sync(
    starting_agent=analyst_agent,
    input=result.final_output.summary
)

# print("### Analyst Agent Output ### \n")
# print(analysis_result.final_output.summary)


class FinalSummary(BaseModel):
    short_summary: str
    markdown_report: str
    followup_questions: list[str]


write_agent = Agent(
    name="Writer AI",
    instructions="""
        You are a senior market research analyst tasked with generating a executive-level report.
        
        Context:
        - You receive an analysis summary from the analyst agent which has analyzed research notes from the researcher agent.
        - summaries and analsyis generated by helper tools: reasercher_agent and analyst_agent.

        you may call these helpers tools to gather information or clarity if needed

        Instruction:
        Your job is to synthesize the analysis summary provided by the analyst agent and create a comprehensive markdown report that includes:
            - ** executive summary **: write a concise summary (1-2 sentences) that captures the essence of the
            - ** detailed report **: elaborate on the key insights and findings from the analysis summary in a well-structured markdown format.
            - ** follow-up questions **: provide a list of potential follow-up questions for further research

        Input:
        original user query and the analysis summary provided by the analyst agent.
        
        Output:
        return a strucured output containing the following fields:
        - short_summary: a concise summary (1-2 sentences) that captures the essence of the analysis summary.
        - markdown_report: a detailed report in markdown format that elaborates on the key insights and findings from the analysis summary.
        - followup_questions: a list of potential follow-up questions for further research based on the analysis summary.
    """,
    model=model,
    output_type=FinalSummary
)
# print(f"{write_agent.name} Agent created successfully!\n")

print(f"### Running Writer Agent to create a comprehensive markdown report based on the analysis summary provided by Analyst Agent on '{input_text}'? ### \n")
final_report_result = Runner.run_sync(
    starting_agent=write_agent,
    input=analysis_result.final_output.summary
)

# print("### Writer Agent Output ### \n")
# print(f"#### Short Summary: \n {final_report_result.final_output.short_summary} \n")
# print(f"#### Detailed Report: \n {final_report_result.final_output.markdown_report} \n")
# print(f"#### Follow-up Questions: \n {', '.join(final_report_result.final_output.followup_questions)} \n")

# -----------------------------
# 5 Generate DOC File
# -----------------------------
def generate_docx(report_text: str, filename="AI_Report.docx"):

    document = Document()
    document.add_heading("Write Agent Generated Report", level=1)

    for line in report_text.split("\n"):
        document.add_paragraph(line)

    document.save(filename)
    print(f"\n✅ Report saved as {filename}")


print(f"### Generating DOCX file for the report generated by Writer Agent on '{input_text}'? ### \n")
generate_docx(final_report_result.final_output.markdown_report, filename="day-2/Final_Report.docx")